from settings_namespace import VARIABLES_FILE_NAME

TEXT_EDITOR_VARIABLE="TEXT_EDITOR"
LATEX_SUBSTITUTIONS_VARIABLE="LATEX_SUBS"
VARIABLES_FILE=VARIABLES_FILE_NAME
VAR_COMMAND_FORMAT = r'^\\var{(\w+)}|([^\\])\\var{(\w+)}'
