ENCODING='utf-8'
SETTINGS_FILE_NAME = "settings.json"

BASE_FILES: str = "baseFiles"
SOURCE_FILES: str = "sourceFiles"
GENERATED_FILES: str = "generatedFiles"

SETTINGS_FIELDS_LIST = [BASE_FILES, SOURCE_FILES, GENERATED_FILES]
